/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-normal",
    "bg-fire",
    "bg-water",
    "bg-grass",
    "bg-electric",
    "bg-ice",
    "bg-fighting",
    "bg-poison",
    "bg-ground",
    "bg-flying",
    "bg-psychic",
    "bg-bug",
    "bg-rock",
    "bg-ghost",
    "bg-dragon",
    "bg-dark",
    "bg-steel",
    "bg-fairy",
    "from-normal",
    "from-fire",
    "from-water",
    "from-grass",
    "from-electric",
    "from-ice",
    "from-fighting",
    "from-poison",
    "from-ground",
    "from-flying",
    "from-psychic",
    "from-bug",
    "from-rock",
    "from-ghost",
    "from-dragon",
    "from-dark",
    "from-steel",
    "from-fairy",
    "to-normal",
    "to-fire",
    "to-water",
    "to-grass",
    "to-electric",
    "to-ice",
    "to-fighting",
    "to-poison",
    "to-ground",
    "to-flying",
    "to-psychic",
    "to-bug",
    "to-rock",
    "to-ghost",
    "to-dragon",
    "to-dark",
    "to-steel",
    "to-fairy",
    "bg-gradient-to-r",
    "bg-normal-badge",
    "bg-fire-badge",
    "bg-water-badge",
    "bg-grass-badge",
    "bg-electric-badge",
    "bg-ice-badge",
    "bg-fighting-badge",
    "bg-poison-badge",
    "bg-ground-badge",
    "bg-flying-badge",
    "bg-psychic-badge",
    "bg-bug-badge",
    "bg-rock-badge",
    "bg-ghost-badge",
    "bg-dragon-badge",
    "bg-dark-badge",
    "bg-steel-badge",
    "bg-fairy-badge",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#9181a1",
        secondary: "#2c2a4a",
        tertiary: "#d9cfc1",
        quaternary: "#a8c3d1",
        quinary: "#d67e61",
        senary: "#8ba88f",
        // Pokemon types
        normal: "#d9d5c9",
        fire: "#ffd1b5",
        water: "#b3d9ff",
        grass: "#cdebb0",
        electric: "#fff5b8",
        ice: "#d0f6f9",
        fighting: "#e8b2a9",
        poison: "#d9b3dd",
        ground: "#e6d3b3",
        flying: "#d6d5f9",
        psychic: "#f7c0d9",
        bug: "#d2e8a3",
        rock: "#ddd1bb",
        ghost: "#c5b9dd",
        dragon: "#c7b9e9",
        dark: "#b7b7bb",
        steel: "#d1d1e0",
        fairy: "#fad6e6",

        // Pokemon types badges
        "normal-badge": "#a8a77a",
        "fire-badge": "#ee8130",
        "water-badge": "#6390f0",
        "grass-badge": "#7ac74c",
        "electric-badge": "#f7d02c",
        "ice-badge": "#96d9d6",
        "fighting-badge": "#c22e28",
        "poison-badge": "#a33ea1",
        "ground-badge": "#e2bf65",
        "flying-badge": "#a98ff3",
        "psychic-badge": "#f95587",
        "bug-badge": "#a6b91a",
        "rock-badge": "#b6a136",
        "ghost-badge": "#735797",
        "dragon-badge": "#6f35fc",
        "dark-badge": "#705746",
        "steel-badge": "#b7b7ce",
        "fairy-badge": "#d685ad",
      },
    },
  },
  plugins: [],
};
